// Fill out your copyright notice in the Description page of Project Settings.


#include "Characters/DroneCharacter.h"
#include "GAS/SignalAbilitySystemComponent.h"
#include "GAS/Attributes/DroneCoreAttributeSet.h"
#include "AbilitySystemComponent.h"
#include "Components/SpotLightComponent.h"
#include "GameplayEffect.h"
#include "SignalGameplayTags.h"
#include "GameFramework/CharacterMovementComponent.h"

// Sets default values
ADroneCharacter::ADroneCharacter()
{
	PrimaryActorTick.bCanEverTick = true;
	PrimaryActorTick.bStartWithTickEnabled = true;

	AbilitySystemComp = CreateDefaultSubobject<USignalAbilitySystemComponent>(TEXT("AbilitySystemComp"));
	AbilitySystemComp->SetIsReplicated(true);

	DroneAttributes = CreateDefaultSubobject<UDroneCoreAttributeSet>(TEXT("DroneAttributes"));

	DroneLight = CreateDefaultSubobject<USpotLightComponent>("DroneLight");
	DroneLight->SetupAttachment(GetRootComponent());
	DroneLight->SetRelativeLocation(FVector(40.f, 0.f, 5.f));
	DroneLight->SetVisibility(false);

	UCharacterMovementComponent* MoveComp = GetCharacterMovement();
	if (MoveComp)
	{
		MoveComp->DefaultLandMovementMode = MOVE_Flying;
		MoveComp->bOrientRotationToMovement = false;
		MoveComp->GravityScale = 0.0f;          // ì¤‘ë ¥ ì œê±°
	}

	bUseControllerRotationYaw = true;
}

// Called when the game starts or when spawned
void ADroneCharacter::BeginPlay()
{
	Super::BeginPlay();
	
	if (AbilitySystemComp)
	{
		AbilitySystemComp->InitAbilityActorInfo(this, this);
		InitializeAttributes();
		GiveStartupAbilities();

		const FSignalGameplayTags& SignalTags = FSignalGameplayTags::Get();
		AbilitySystemComp->TryActivateAbilitiesByTag(FGameplayTagContainer(SignalTags.Ability_Drone_PassiveBattery));
	}

}


void ADroneCharacter::Tick(float DeltaSeconds)
{
	Super::Tick(DeltaSeconds);

	// ë©”ì‰¬ ê¸°ì¤€ìœ¼ë¡œë§Œ ê¸°ìš¸ì´ê¸° (ìº¡ìŠì€ ê·¸ëŒ€ë¡œ)
	USkeletalMeshComponent* MeshComp = GetMesh();
	if (!MeshComp)
	{
		return;
	}

	const FVector Vel = GetVelocity();

	// ìˆ˜í‰ ì†ë„ë§Œ ì‚¬ìš©í•´ì„œ í‹¸íŠ¸ ê³„ì‚°
	const FVector HorizontalVel(Vel.X, Vel.Y, 0.f);
	const float Speed = HorizontalVel.Size();

	float TargetPitch = 0.f;
	float TargetRoll = 0.f;

	if (Speed > MinSpeedForTilt)
	{
		// ì›”ë“œ â†’ ë¡œì»¬ ì†ë„ ë²¡í„°ë¡œ ë³€í™˜
		const FRotator ActorRot = GetActorRotation();
		const FVector LocalVel = ActorRot.UnrotateVector(Vel);

		FVector2D LocalDir(LocalVel.X, LocalVel.Y);
		if (!LocalDir.IsNearlyZero())
		{
			LocalDir.Normalize();

			// ì „ì§„(ì•ž)ì¼ìˆ˜ë¡ Pitch(-), í›„ì§„ì¼ìˆ˜ë¡ Pitch(+)
			TargetPitch = -LocalDir.X * MaxTiltAngle;

			// ì˜¤ë¥¸ìª½ ì´ë™ì¼ìˆ˜ë¡ Roll(+), ì™¼ìª½ ì´ë™ì¼ìˆ˜ë¡ Roll(-)
			TargetRoll = LocalDir.Y * MaxTiltAngle;
		}
	}

	const FRotator CurrentRot = MeshComp->GetRelativeRotation();
	// YawëŠ” ê¸°ì¡´ ê°’ ìœ ì§€ (íšŒì „ì€ ì»¨íŠ¸ë¡¤ëŸ¬ê°€ ë‹´ë‹¹)
	const FRotator TargetRot(TargetPitch, CurrentRot.Yaw, TargetRoll);

	const FRotator NewRot =
		FMath::RInterpTo(CurrentRot, TargetRot, DeltaSeconds, TiltInterpSpeed);

	MeshComp->SetRelativeRotation(NewRot);
}

void ADroneCharacter::HandleMoveInput(const FVector2D& MoveVector)
{
	if (!Controller)
	{
		return;
	}

	// ì»¨íŠ¸ë¡¤ëŸ¬ì˜ Yaw ê¸°ì¤€ìœ¼ë¡œ ì „/í›„/ì¢Œ/ìš° ê³„ì‚°
	const FRotator ControlRot = Controller->GetControlRotation();
	const FRotator YawRot(0.f, ControlRot.Yaw, 0.f);

	const FVector ForwardDir = FRotationMatrix(YawRot).GetUnitAxis(EAxis::X);
	const FVector RightDir = FRotationMatrix(YawRot).GetUnitAxis(EAxis::Y);

	if (!FMath::IsNearlyZero(MoveVector.Y))
	{
		AddMovementInput(ForwardDir, MoveVector.Y);
	}
	if (!FMath::IsNearlyZero(MoveVector.X))
	{
		AddMovementInput(RightDir, MoveVector.X);
	}
}

void ADroneCharacter::HandleUpDownInput(float Value)
{
	if (!Controller)
	{
		return;
	}

	if (FMath::IsNearlyZero(Value))
	{
		return;
	}

	const FVector UpDir = FVector::UpVector; // (0,0,1)
	AddMovementInput(UpDir, Value);
}

void ADroneCharacter::HandleStop()
{
	UCharacterMovementComponent* MoveComp = GetCharacterMovement();
	if (MoveComp)
	{
		MoveComp->StopMovementImmediately();
	}
}

UAbilitySystemComponent* ADroneCharacter::GetAbilitySystemComponent() const
{
	return AbilitySystemComp;
}


void ADroneCharacter::InitializeAttributes()
{
	if (AbilitySystemComp && DefaultAttributeEffect)
	{
		FGameplayEffectContextHandle Context = AbilitySystemComp->MakeEffectContext();
		Context.AddSourceObject(this);

		FGameplayEffectSpecHandle SpecHandle = AbilitySystemComp->MakeOutgoingSpec(DefaultAttributeEffect, 1.f, Context);
		if (SpecHandle.IsValid())
		{
			AbilitySystemComp->ApplyGameplayEffectSpecToSelf(*SpecHandle.Data.Get());
		}
	}
}

void ADroneCharacter::GiveStartupAbilities()
{
	if (!AbilitySystemComp) 
	{
		return;
	}

	for (TSubclassOf<UGameplayAbility>& AbilityClass : StartupAbilities)
	{
		if (*AbilityClass)
		{
			AbilitySystemComp->GiveAbility(
				FGameplayAbilitySpec(AbilityClass, 1, INDEX_NONE, this));
		}
	}
	// ðŸ”» ì—¬ê¸°ì„œ ì‹¤ì œ ASCê°€ ê°€ì§€ê³  ìžˆëŠ” ì–´ë¹Œë¦¬í‹° ëª©ë¡ ë¡œê·¸ ì°ê¸°
	for (const FGameplayAbilitySpec& Spec : AbilitySystemComp->GetActivatableAbilities())
	{
		if (Spec.Ability)
		{
			FString TagString = Spec.DynamicAbilityTags.ToString();

			UE_LOG(LogTemp, Warning, TEXT("ASC Ability: %s | DynamicTags: %s"),
				*Spec.Ability->GetName(),
				*TagString);
		}
	}
}





